---
# tasks file for deploy_jenkins
- name: install wget
  apt: name=wget state=latest

- name: Install  Java
  apt: name=openjdk-8-jre state=latest

- name: Import the GPG keys of the Jenkins repository
  apt_key:
       url: https://pkg.jenkins.io/debian/jenkins.io.key
       state: present

- name: Download jenkins.repo
  apt_repository:
       repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
       state: present


- name: Install Jenkins
  apt: name=jenkins state=latest

- name: Wait 30 second
  wait_for: timeout=30

- name: Get init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Print init password Jenkins
  debug:
   var: result.stdout
